
package com.inherente.dummy.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HostService", targetNamespace = "http://localhost:7001/nothing/HostService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HostService {


    /**
     * 
     * @param getGreeting
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getGreetingResponse", targetNamespace = "http://localhost:7001/nothing/HostService", partName = "getGreetingResponse")
    public String getGreeting(
        @WebParam(name = "getGreeting", targetNamespace = "http://localhost:7001/nothing/HostService", partName = "getGreeting")
        String getGreeting);

}
