WHENEVER SQLERROR CONTINUE
DROP USER dev_nothing_adm CASCADE;
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER dev_nothing_adm
IDENTIFIED BY SY7FIg1uUhQEQeLFuTAy;

GRANT RESOURCE TO dev_nothing_adm;
GRANT CONNECT TO dev_nothing_adm;

ALTER USER dev_nothing_adm DEFAULT ROLE ALL;

GRANT UNLIMITED TABLESPACE TO dev_nothing_adm;
GRANT CREATE VIEW TO dev_nothing_adm;

ALTER USER dev_nothing_adm QUOTA UNLIMITED ON USERS;

GRANT SELECT ON SYS.V_$SESSION TO dev_nothing_adm;

COMMIT ;
